# Site Settings
title: MELANCHOLY14's blog
email: melancholy14@hotmail.com
description: Welcome to my technical blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://melancholy14.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Misol Goh
user_description: Front-end Full-stack developer / Travel Lover
blogname: DON'T PANIC
disqus_username: misolgoh

# Social Media
# Remove the item if you don't need it
github_username: melancholy14
facebook_username: melancholy14
twitter_username: msg1y15
instagram_username: 1989.03.14
linkedin_username: melancholy14
medium_username: 19890314

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
